# Generated by Django 4.1.2 on 2022-10-19 08:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ip', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ImageTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_base64', models.CharField(max_length=30)),
                ('origin_base64', models.CharField(max_length=30)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.camera')),
            ],
        ),
        migrations.CreateModel(
            name='Centroids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(max_length=100)),
                ('y', models.CharField(max_length=100)),
                ('image_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.imagetransaction')),
            ],
        ),
    ]
