# Generated by Django 4.1.2 on 2022-10-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AlterField(
            model_name='centroids',
            name='x',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='centroids',
            name='y',
            field=models.IntegerField(),
        ),
    ]
