# Generated by Django 4.1.2 on 2022-10-31 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_delete_users_alter_centroids_x_alter_centroids_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetransaction',
            name='origin_base64',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='imagetransaction',
            name='output_base64',
            field=models.CharField(max_length=100000),
        ),
    ]
