version: '3.3'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: web
    restart: always
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - ../.:/usr/src/django
    ports:
      - 8000:8000
    env_file:
      - dev.env
  db:
    container_name: db
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - db.env
volumes:
  postgres_data: