version: '3.3'

volumes:
    postgres_data:

services:
    web:
      build:
        context: ..
        dockerfile: docker/Dockerfile
      container_name: web
      entrypoint: ["wait.sh"]
      restart: always
      command: [
        "python",
        "manage.py",
        "runserver",
        "0.0.0.0:8000"
        ]
      depends_on:
        db:
          condition: service_healthy
        redis:
          condition: service_started
      volumes:
        - ../.:/usr/src/django
      ports:
        - 3000:3000
        - 8000:8000
      env_file:
        - env/dev.env
      working_dir: /usr/src/django/src

    db:
      container_name: db
      image: postgres:13.7
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      env_file:
        - env/db.env
      ports:
            - "5432:5432"
      healthcheck:
        test: "exit 0"

    debug:
      build:
        context: ..
        dockerfile: docker/Dockerfile
      entrypoint: ["wait.sh"]
      ports:
        - "5888:5888"
      command: [
        "python",
        "-m",
        "debugpy",
        "--listen",
        "0.0.0.0:5888",
        "--wait-for-client",
        "-m",
        "pytest",
        "spencer/module/mytasks/tests/tests.py"
        ]
      depends_on:
        - db
      volumes:
        - ../.:/usr/src/django
      env_file:
        - env/dev.env
      working_dir: /usr/src/django/src

    celery:
      build:
        context: ..
        dockerfile: docker/Dockerfile
      container_name: Celery
      entrypoint: ["wait.sh"]
      restart: always
      command: [
        "python",
        "-m",
        "celery",
        "-A",
        "settings",
        "worker",
        "-l",
        "INFO",
        "--autoscale=10,3"
        ]
      # command: cd src/ && python -m celery -A settings worker
      depends_on:
        - web
        - redis
        - db
      volumes:
        - ../.:/usr/src/django
      env_file:
        - env/dev.env
      working_dir: /usr/src/django/src

    celery-beat:
      build:
        context: ..
        dockerfile: docker/Dockerfile
      container_name: Celery-beat
      entrypoint: ["wait.sh"]
      restart: always
      command: [
        "python",
        "-m",
        "celery",
        "-A",
        "settings",
        "beat",
        "-l",
        "info",
        "--scheduler",
        "django_celery_beat.schedulers:DatabaseScheduler",
        "--pidfile="
        ]
      depends_on:
        - web
        - redis
        - db
      volumes:
        - ../.:/usr/src/django
      env_file:
        - env/dev.env
      working_dir: /usr/src/django/src

    redis:
      image: redis
      container_name: redis
      ports:
            - "15672:15672"
            - "5672:5672"
