version: '3.3'

volumes:
    postgres_data:

services:
    web:
      build:
        context: ..
        dockerfile: docker/Dockerfile
      container_name: web
      entrypoint: ["wait.sh"]
      restart: always
      command: [
        "python",
        "src/manage.py",
        "runserver",
        "0.0.0.0:8000"
        ]
      depends_on:
        - db
      volumes:
        - ../.:/usr/src/django
      ports:
        - 3000:3000
        - 8000:8000
      env_file:
        - dev.env

    db:
      container_name: db
      image: postgres:14.5
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      env_file:
        - db.env
      ports:
            - "5432:5432"

    debug:
      build:
        context: ..
        dockerfile: docker/Dockerfile
      entrypoint: ["wait.sh"]
      ports:
              - "5888:5888"
      command: [
        "python",
        "-m",
        "debugpy",
        "--listen",
        "0.0.0.0:5888",
        "--wait-for-client",
        "-m",
        "pytest",
        ""
        ]
      depends_on:
        - db
      volumes:
        - ../.:/usr/src/django
      env_file:
        - dev.env